//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculator
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalculatorData
    {
        public int Id { get; set; }
        public string CurrNumberString { get; set; }
        public string Expression { get; set; }
        public string LastEntry { get; set; }
        public int FirstNumber { get; set; }
        public int SecondNumber { get; set; }
        public string Operand { get; set; }
    }
}
